export const STATIC_TEAMS = [
  {
    id: "arizona-diamondbacks",
    name: "Arizona Diamondbacks",
    abbrs: ["ARI"],
    logoURL: "arizona-diamondbacks",
    abbreviation: "ARI",
  },
  {
    id: "atlanta-braves",
    name: "Atlanta Braves",
    abbrs: ["ATL", "BSN", "MLN"],
    logoURL: "atlanta-braves",
    abbreviation: "ATL",
  },
  {
    id: "baltimore-orioles",
    name: "Baltimore Orioles",
    abbrs: ["BAL", "MLA", "SLB"],
    logoURL: "baltimore-orioles",
    abbreviation: "BAL",
  },
  {
    id: "boston-red-sox",
    name: "Boston Red Sox",
    abbrs: ["BOS"],
    logoURL: "boston-red-sox",
    abbreviation: "BOS",
  },
  {
    id: "chicago-cubs",
    name: "Chicago Cubs",
    abbrs: ["CHC"],
    logoURL: "chicago-cubs",
    abbreviation: "CHC",
  },
  {
    id: "chicago-white-sox",
    name: "Chicago White Sox",
    abbrs: ["CHW"],
    logoURL: "chicago-white-sox",
    abbreviation: "CHW",
  },
  {
    id: "cincinnati-reds",
    name: "Cincinnati Reds",
    abbrs: ["CIN"],
    logoURL: "cincinnati-reds",
    abbreviation: "CIN",
  },
  {
    id: "cleveland-guardians",
    name: "Cleveland Guardians",
    abbrs: ["CLE"],
    logoURL: "cleveland-guardians",
    abbreviation: "CLE",
  },
  {
    id: "colorado-rockies",
    name: "Colorado Rockies",
    abbrs: ["COL"],
    logoURL: "colorado-rockies",
    abbreviation: "COL",
  },
  {
    id: "detroit-tigers",
    name: "Detroit Tigers",
    abbrs: ["DET"],
    logoURL: "detroit-tigers",
    abbreviation: "DET",
  },
  {
    id: "houston-astros",
    name: "Houston Astros",
    abbrs: ["HOU"],
    logoURL: "houston-astros",
    abbreviation: "HOU",
  },
  {
    id: "kansas-city-royals",
    name: "Kansas City Royals",
    abbrs: ["KCR"],
    logoURL: "kansas-city-royals",
    abbreviation: "KCR",
  },
  {
    id: "los-angeles-angels",
    name: "Los Angeles Angels",
    abbrs: ["ANA", "CAL", "LAA"],
    logoURL: "los-angeles-angels",
    abbreviation: "ANA",
  },
  {
    id: "los-angeles-dodgers",
    name: "Los Angeles Dodgers",
    abbrs: ["BRO", "LAD"],
    logoURL: "los-angeles-dodgers",
    abbreviation: "BRO",
  },
  {
    id: "miami-marlins",
    name: "Miami Marlins",
    abbrs: ["FLA", "MIA"],
    logoURL: "miami-marlins",
    abbreviation: "FLA",
  },
  {
    id: "milwaukee-brewers",
    name: "Milwaukee Brewers",
    abbrs: ["MIL", "SEP"],
    logoURL: "milwaukee-brewers",
    abbreviation: "MIL",
  },
  {
    id: "minnesota-twins",
    name: "Minnesota Twins",
    abbrs: ["MIN", "WSH"],
    logoURL: "minnesota-twins",
    abbreviation: "MIN",
  },
  {
    id: "new-york-mets",
    name: "New York Mets",
    abbrs: ["NYM"],
    logoURL: "new-york-mets",
    abbreviation: "NYM",
  },
  {
    id: "new-york-yankees",
    name: "New York Yankees",
    abbrs: ["NYY"],
    logoURL: "new-york-yankees",
    abbreviation: "NYY",
  },
  {
    id: "oakland-athletics",
    name: "Oakland Athletics",
    abbrs: ["ATH", "KCA", "OAK", "PHA"],
    logoURL: "oakland-athletics",
    abbreviation: "ATH",
  },
  {
    id: "philadelphia-phillies",
    name: "Philadelphia Phillies",
    abbrs: ["PHI"],
    logoURL: "philadelphia-phillies",
    abbreviation: "PHI",
  },
  {
    id: "pittsburgh-pirates",
    name: "Pittsburgh Pirates",
    abbrs: ["PIT"],
    logoURL: "pittsburgh-pirates",
    abbreviation: "PIT",
  },
  {
    id: "san-diego-padres",
    name: "San Diego Padres",
    abbrs: ["SDP"],
    logoURL: "san-diego-padres",
    abbreviation: "SDP",
  },
  {
    id: "san-francisco-giants",
    name: "San Francisco Giants",
    abbrs: ["NYG", "SFG"],
    logoURL: "san-francisco-giants",
    abbreviation: "NYG",
  },
  {
    id: "seattle-mariners",
    name: "Seattle Mariners",
    abbrs: ["SEA"],
    logoURL: "seattle-mariners",
    abbreviation: "SEA",
  },
  {
    id: "st-louis-cardinals",
    name: "St. Louis Cardinals",
    abbrs: ["STL"],
    logoURL: "st-louis-cardinals",
    abbreviation: "STL",
  },
  {
    id: "tampa-bay-rays",
    name: "Tampa Bay Rays",
    abbrs: ["TBD", "TBR"],
    logoURL: "tampa-bay-rays",
    abbreviation: "TBD",
  },
  {
    id: "texas-rangers",
    name: "Texas Rangers",
    abbrs: ["TEX", "WSA"],
    logoURL: "texas-rangers",
    abbreviation: "TEX",
  },
  {
    id: "toronto-blue-jays",
    name: "Toronto Blue Jays",
    abbrs: ["TOR"],
    logoURL: "toronto-blue-jays",
    abbreviation: "TOR",
  },
  {
    id: "washington-nationals",
    name: "Washington Nationals",
    abbrs: ["MON", "WSN"],
    logoURL: "washington-nationals",
    abbreviation: "MON",
  },
];